#ifndef CORE_APP_CONTROL_FLIGHTCONTROLLER_FLIGHT_CONTROLLER_H_
#define CORE_APP_CONTROL_FLIGHTCONTROLLER_FLIGHT_CONTROLLER_H_

void FlightController_InitMotorOutputs(void);
void RESET_ALL_PID(void);
void MPC(void);

#endif /* CORE_APP_CONTROL_FLIGHTCONTROLLER_FLIGHT_CONTROLLER_H_ */
