#ifndef CORE_APP_SENSORS_MAGNETOMETER_MAGNETOMETER_SENSOR_H_
#define CORE_APP_SENSORS_MAGNETOMETER_MAGNETOMETER_SENSOR_H_

void HMC5883L_Init(void);
void COMPASS_PROCESS(void);

#endif /* CORE_APP_SENSORS_MAGNETOMETER_MAGNETOMETER_SENSOR_H_ */
